import { ToothInfo, DentalService, ClinicInfo, BeforeAfterCase, ClinicSettings } from '../types';

export const FDI_TEETH: ToothInfo[] = [
  // Upper Right (Quadrant 1) - FDI 18 down to 11
  { fdiNumber: 18, quadrant: 1, nameAr: 'ضرس العقل العلوي الأيمن', nameEn: 'Upper Right 3rd Molar (Wisdom)', type: 'wisdom' },
  { fdiNumber: 17, quadrant: 1, nameAr: 'الضرس الثاني العلوي الأيمن', nameEn: 'Upper Right 2nd Molar', type: 'molar' },
  { fdiNumber: 16, quadrant: 1, nameAr: 'الضرس الأول العلوي الأيمن', nameEn: 'Upper Right 1st Molar', type: 'molar' },
  { fdiNumber: 15, quadrant: 1, nameAr: 'الضاحك الثاني العلوي الأيمن', nameEn: 'Upper Right 2nd Premolar', type: 'premolar' },
  { fdiNumber: 14, quadrant: 1, nameAr: 'الضاحك الأول العلوي الأيمن', nameEn: 'Upper Right 1st Premolar', type: 'premolar' },
  { fdiNumber: 13, quadrant: 1, nameAr: 'الناب العلوي الأيمن', nameEn: 'Upper Right Canine', type: 'canine' },
  { fdiNumber: 12, quadrant: 1, nameAr: 'القاطع الجانبي العلوي الأيمن', nameEn: 'Upper Right Lateral Incisor', type: 'incisor' },
  { fdiNumber: 11, quadrant: 1, nameAr: 'القاطع المركزي العلوي الأيمن', nameEn: 'Upper Right Central Incisor', type: 'incisor' },

  // Upper Left (Quadrant 2) - FDI 21 up to 28
  { fdiNumber: 21, quadrant: 2, nameAr: 'القاطع المركزي العلوي الأيسر', nameEn: 'Upper Left Central Incisor', type: 'incisor' },
  { fdiNumber: 22, quadrant: 2, nameAr: 'القاطع الجانبي العلوي الأيسر', nameEn: 'Upper Left Lateral Incisor', type: 'incisor' },
  { fdiNumber: 23, quadrant: 2, nameAr: 'الناب العلوي الأيسر', nameEn: 'Upper Left Canine', type: 'canine' },
  { fdiNumber: 24, quadrant: 2, nameAr: 'الضاحك الأول العلوي الأيسر', nameEn: 'Upper Left 1st Premolar', type: 'premolar' },
  { fdiNumber: 25, quadrant: 2, nameAr: 'الضاحك الثاني العلوي الأيسر', nameEn: 'Upper Left 2nd Premolar', type: 'premolar' },
  { fdiNumber: 26, quadrant: 2, nameAr: 'الضرس الأول العلوي الأيسر', nameEn: 'Upper Left 1st Molar', type: 'molar' },
  { fdiNumber: 27, quadrant: 2, nameAr: 'الضرس الثاني العلوي الأيسر', nameEn: 'Upper Left 2nd Molar', type: 'molar' },
  { fdiNumber: 28, quadrant: 2, nameAr: 'ضرس العقل العلوي الأيسر', nameEn: 'Upper Left 3rd Molar (Wisdom)', type: 'wisdom' },

  // Lower Left (Quadrant 3) - FDI 38 down to 31
  { fdiNumber: 38, quadrant: 3, nameAr: 'ضرس العقل السفلي الأيسر', nameEn: 'Lower Left 3rd Molar (Wisdom)', type: 'wisdom' },
  { fdiNumber: 37, quadrant: 3, nameAr: 'الضرس الثاني السفلي الأيسر', nameEn: 'Lower Left 2nd Molar', type: 'molar' },
  { fdiNumber: 36, quadrant: 3, nameAr: 'الضرس الأول السفلي الأيسر', nameEn: 'Lower Left 1st Molar', type: 'molar' },
  { fdiNumber: 35, quadrant: 3, nameAr: 'الضاحك الثاني السفلي الأيسر', nameEn: 'Lower Left 2nd Premolar', type: 'premolar' },
  { fdiNumber: 34, quadrant: 3, nameAr: 'الضاحك الأول السفلي الأيسر', nameEn: 'Lower Left 1st Premolar', type: 'premolar' },
  { fdiNumber: 33, quadrant: 3, nameAr: 'الناب السفلي الأيسر', nameEn: 'Lower Left Canine', type: 'canine' },
  { fdiNumber: 32, quadrant: 3, nameAr: 'القاطع الجانبي السفلي الأيسر', nameEn: 'Lower Left Lateral Incisor', type: 'incisor' },
  { fdiNumber: 31, quadrant: 3, nameAr: 'القاطع المركزي السفلي الأيسر', nameEn: 'Lower Left Central Incisor', type: 'incisor' },

  // Lower Right (Quadrant 4) - FDI 41 up to 48
  { fdiNumber: 41, quadrant: 4, nameAr: 'القاطع المركزي السفلي الأيمن', nameEn: 'Lower Right Central Incisor', type: 'incisor' },
  { fdiNumber: 42, quadrant: 4, nameAr: 'القاطع الجانبي السفلي الأيمن', nameEn: 'Lower Right Lateral Incisor', type: 'incisor' },
  { fdiNumber: 43, quadrant: 4, nameAr: 'الناب السفلي الأيمن', nameEn: 'Lower Right Canine', type: 'canine' },
  { fdiNumber: 44, quadrant: 4, nameAr: 'الضاحك الأول السفلي الأيمن', nameEn: 'Lower Right 1st Premolar', type: 'premolar' },
  { fdiNumber: 45, quadrant: 4, nameAr: 'الضاحك الثاني السفلي الأيمن', nameEn: 'Lower Right 2nd Premolar', type: 'premolar' },
  { fdiNumber: 46, quadrant: 4, nameAr: 'الضرس الأول السفلي الأيمن', nameEn: 'Lower Right 1st Molar', type: 'molar' },
  { fdiNumber: 47, quadrant: 4, nameAr: 'الضرس الثاني السفلي الأيمن', nameEn: 'Lower Right 2nd Molar', type: 'molar' },
  { fdiNumber: 48, quadrant: 4, nameAr: 'ضرس العقل السفلي الأيمن', nameEn: 'Lower Right 3rd Molar (Wisdom)', type: 'wisdom' },
];

export const SYMPTOMS_LIST = [
  { id: 'sharp_pain', nameAr: 'ألم حاد ومفاجئ', nameEn: 'Sharp Sudden Pain', icon: 'zap' },
  { id: 'sensitivity_cold', nameAr: 'حساسية مع المشروبات الباردة', nameEn: 'Cold Sensitivity', icon: 'thermometer-snowflake' },
  { id: 'sensitivity_hot', nameAr: 'حساسية مع المشروبات الساخنة', nameEn: 'Hot Sensitivity', icon: 'thermometer-sun' },
  { id: 'throbbing', nameAr: 'ألم نابض مستمر (خاصة ليلاً)', nameEn: 'Continuous Throbbing Pain', icon: 'activity' },
  { id: 'gum_bleeding', nameAr: 'نزيف اللثة أثناء تنظيف الأسنان', nameEn: 'Bleeding Gums', icon: 'droplet' },
  { id: 'gum_swelling', nameAr: 'تورم أو انتفاخ في اللثة أو الخد', nameEn: 'Gum or Facial Swelling', icon: 'alert-circle' },
  { id: 'broken_tooth', nameAr: 'كسر في السن أو سقوط حشو قديم', nameEn: 'Broken Tooth or Lost Filling', icon: 'shield-alert' },
  { id: 'chewing_pain', nameAr: 'ألم وصعوبة عند مضغ الطعام', nameEn: 'Pain While Chewing', icon: 'utensils' },
  { id: 'loose_tooth', nameAr: 'خلخلة أو حركة في السن', nameEn: 'Loose Tooth', icon: 'move' },
  { id: 'bad_breath', nameAr: 'رائحة فم كريهة مستمرة أو طعم مر', nameEn: 'Persistent Bad Breath', icon: 'wind' },
];

export const DEFAULT_SERVICES: DentalService[] = [
  {
    id: 'srv_consult',
    nameAr: 'كشف واستشارة شاملة',
    nameEn: 'Comprehensive Exam & Consultation',
    descriptionAr: 'فحص سريري كامل للأسنان واللثة مع خطة علاجية مخصصة',
    descriptionEn: 'Full clinical examination of teeth & gums with customized treatment plan',
    estimatedPrice: 150,
    durationMinutes: 30,
    iconName: 'Stethoscope',
    category: 'checkup',
  },
  {
    id: 'srv_scaling',
    nameAr: 'تنظيف الجير وتلميع الأسنان',
    nameEn: 'Scaling & Polishing',
    descriptionAr: 'إزالة الرواسب الجيرية وتلميع الأسنان بالموجات فوق الصوتية',
    descriptionEn: 'Ultrasonic calculus removal and teeth polishing for healthy gums',
    estimatedPrice: 350,
    durationMinutes: 45,
    iconName: 'Sparkles',
    category: 'restoration',
  },
  {
    id: 'srv_whitening',
    nameAr: 'تبييض الأسنان بالليزر',
    nameEn: 'In-Office Laser Teeth Whitening',
    descriptionAr: 'تفتيح لون الأسنان حتى 8 درجات في جلسة واحدة آمنة',
    descriptionEn: 'Brighten teeth up to 8 shades in a single safe, effective session',
    estimatedPrice: 1200,
    durationMinutes: 60,
    iconName: 'Smile',
    category: 'cosmetics',
  },
  {
    id: 'srv_filling',
    nameAr: 'حشو تجميلي ليزر (كومبوزيت)',
    nameEn: 'Composite Cosmetic Filling',
    descriptionAr: 'حشو بلون السن الطبيعي يدوم طويلاً ويعالج التسوس',
    descriptionEn: 'Tooth-colored aesthetic resin filling to restore cavity and shape',
    estimatedPrice: 450,
    durationMinutes: 40,
    iconName: 'Layers',
    category: 'restoration',
  },
  {
    id: 'srv_root_canal',
    nameAr: 'علاج وحشو العصب بجلسة واحدة',
    nameEn: 'Single-Visit Root Canal Treatment',
    descriptionAr: 'تنظيف قنوات العصب بأحدث الأجهزة الدوارة بدون ألم',
    descriptionEn: 'Painless rotary endodontic treatment to save infected tooth',
    estimatedPrice: 800,
    durationMinutes: 60,
    iconName: 'HeartPulse',
    category: 'endodontics',
  },
  {
    id: 'srv_zirconia',
    nameAr: 'تركيب تاج زركونيا ألماني',
    nameEn: 'German Zirconia Crown',
    descriptionAr: 'تلبيسة أسنان متينة وطبيعية بنسبة 100% بدون معدن',
    descriptionEn: 'Metal-free, highly aesthetic and durable zirconia restoration',
    estimatedPrice: 1500,
    durationMinutes: 45,
    iconName: 'Shield',
    category: 'cosmetics',
  },
  {
    id: 'srv_implant',
    nameAr: 'زراعة الأسنان الفورية الألمانية',
    nameEn: 'Immediate Dental Implant',
    descriptionAr: 'غرسة تيتانيوم من أفضل الشركات العالمية مع ضمان مدى الحياة',
    descriptionEn: 'Premium titanium implant fixture with lifetime warranty',
    estimatedPrice: 6000,
    durationMinutes: 60,
    iconName: 'Anchor',
    category: 'surgery',
  },
];

export const CLINIC_INFO: ClinicInfo = {
  nameAr: 'منصة اسنانجي الطبية',
  nameEn: 'Asnanji Dental Platform',
  doctorNameAr: 'أطباء اسنانجي المعتمدون',
  doctorNameEn: 'Certified Asnanji Dentists',
  doctorTitleAr: 'استشاريو طب وجراحة وتجميل الأسنان',
  doctorTitleEn: 'Dental Specialists & Surgeons',
  addressAr: 'فروع متعددة - القاهرة والجيزة ومحافظات مصر',
  addressEn: 'Multiple Branches - Cairo, Giza & Across Egypt',
  phone: '+20 100 000 0000',
  whatsapp: '+20 100 000 0000',
  workingDaysAr: 'السبت إلى الخميس',
  workingDaysEn: 'Saturday to Thursday',
  workingHoursAr: 'يومياً من 10:00 صباحاً حتى 10:00 مساءً',
  workingHoursEn: 'Daily 10:00 AM - 10:00 PM',
  mapLatitude: 30.0444,
  mapLongitude: 31.2357,
  experienceYears: 12,
  rating: 4.9,
  reviewCount: 385,
};

export const DEFAULT_CLINIC_SETTINGS: ClinicSettings = {
  id: 'clinic_main',
  doctorName: 'أطباء اسنانجي',
  doctorTitle: 'استشاريو طب وجراحة الأسنان',
  doctorBio: 'نخبة من أفضل أطباء الأسنان في مصر لتقديم أرقى خدمات الرعاية والتشخيص الفوري.',
  avatarUrl: '',
  coverImageUrl: '',
  yearsExperience: 12,
  patientsCount: 1500,
  rating: 4.9,
  phoneNumber: '+20 100 000 0000',
  whatsappNumber: '+20 100 000 0000',
  locationAddress: 'القاهرة، مصر',
  locationMapsUrl: '',
  workingHours: '10:00 AM - 10:00 PM',
};

export const INITIAL_BEFORE_AFTER_CASES: BeforeAfterCase[] = [];
export const BEFORE_AFTER_CASES: BeforeAfterCase[] = [];
